export const KEY_CLOAK_TOKEN = "KEY_CLOAK_TOKEN"
export const KEY_CLOAK_AUTHENTICATED = "KEY_CLOAK_AUTHENTICATED"
export const CLEAR_KEYCLOCK_DATA = "CLEAR_KEYCLOCK_DATA"
export const IS_CHECK_KEYCLOAK_AUTHENTICATION = "IS_CHECK_KEYCLOAK_AUTHENTICATION"